version: '3.8'

services:
  ui:
    build:
      context: ./UI
    ports:
      - "5173:80" 
      - app-network

  # Backend Service: URL Service
  url-service:
    build:
      context: ./url-service
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}  # Pass in DB connection string or any other env variables
      - PORT=${PORT:-3000}
    ports:
       - "3000:${PORT:-3000}"
    networks:
      - app-network

  # Backend Service: Redirect Service
  redirect-service:
    build:
      context: ./redirect-service
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - PORT=${PORT:-3001}
    ports:
      - "3001:${PORT:-3001}"
    networks:
      - app-network

  # Backend Service: Click History Service
  click-history-service:
    build:
      context: ./click-history-service
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - PORT=${PORT:-3002}
    ports:
      - "3002:${PORT:-3002}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge